nelmio_cors:
    defaults:
        origin_regex: true
        allow_credentials: true
        allow_origin: ['http://localhost:5173'] 
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-CSRF-TOKEN', 'Accept']
        expose_headers: ['Link']
        max_age: 3600
    paths:
         '^/':
            allow_origin: ['http://localhost:5173']
            allow_headers: ['Content-Type', 'X-CSRF-TOKEN']
            allow_methods: ['POST', 'GET', 'OPTIONS']
            max_age: 3600